//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCrazyZoo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfCrazyZoo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy Zoo.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal added..
        /// </summary>
        public static string Msg_Added {
            get {
                return ResourceManager.GetString("Msg_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be between 1 and 30..
        /// </summary>
        public static string Msg_AgeOutOfRange {
            get {
                return ResourceManager.GetString("Msg_AgeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an integer age..
        /// </summary>
        public static string Msg_AgeRequired {
            get {
                return ResourceManager.GetString("Msg_AgeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy action: {0}.
        /// </summary>
        public static string Msg_Crazy {
            get {
                return ResourceManager.GetString("Msg_Crazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ate {1}..
        /// </summary>
        public static string Msg_Fed {
            get {
                return ResourceManager.GetString("Msg_Fed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food can only contain letters, spaces and dashes..
        /// </summary>
        public static string Msg_FoodInvalid {
            get {
                return ResourceManager.GetString("Msg_FoodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter food..
        /// </summary>
        public static string Msg_FoodRequired {
            get {
                return ResourceManager.GetString("Msg_FoodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can contain only letters, spaces and dashes..
        /// </summary>
        public static string Msg_NameInvalid {
            get {
                return ResourceManager.GetString("Msg_NameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name..
        /// </summary>
        public static string Msg_NameRequired {
            get {
                return ResourceManager.GetString("Msg_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an animal first..
        /// </summary>
        public static string Msg_NoSelection {
            get {
                return ResourceManager.GetString("Msg_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected animal?.
        /// </summary>
        public static string Msg_RemoveConfirmText {
            get {
                return ResourceManager.GetString("Msg_RemoveConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Remove.
        /// </summary>
        public static string Msg_RemoveConfirmTitle {
            get {
                return ResourceManager.GetString("Msg_RemoveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal removed..
        /// </summary>
        public static string Msg_Removed {
            get {
                return ResourceManager.GetString("Msg_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select animal kind..
        /// </summary>
        public static string Msg_SelectKind {
            get {
                return ResourceManager.GetString("Msg_SelectKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string Msg_Sound {
            get {
                return ResourceManager.GetString("Msg_Sound", resourceCulture);
            }
        }
    }
}
