//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCrazyZoo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfCrazyZoo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy Zoo..
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal added..
        /// </summary>
        public static string Msg_Added {
            get {
                return ResourceManager.GetString("Msg_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be between 1 and 30..
        /// </summary>
        public static string Msg_AgeOutOfRange {
            get {
                return ResourceManager.GetString("Msg_AgeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an integer age..
        /// </summary>
        public static string Msg_AgeRequired {
            get {
                return ResourceManager.GetString("Msg_AgeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} noticed {1}.
        /// </summary>
        public static string Msg_AnimalNoticed {
            get {
                return ResourceManager.GetString("Msg_AnimalNoticed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all log entries?.
        /// </summary>
        public static string Msg_ClearLogConfirmText {
            get {
                return ResourceManager.GetString("Msg_ClearLogConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Msg_ClearLogConfirmTitle {
            get {
                return ResourceManager.GetString("Msg_ClearLogConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy action: {0}.
        /// </summary>
        public static string Msg_Crazy {
            get {
                return ResourceManager.GetString("Msg_Crazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} finished eating.
        /// </summary>
        public static string Msg_EatingFinished {
            get {
                return ResourceManager.GetString("Msg_EatingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} starts eating.
        /// </summary>
        public static string Msg_EatingStart {
            get {
                return ResourceManager.GetString("Msg_EatingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ate {1}..
        /// </summary>
        public static string Msg_Fed {
            get {
                return ResourceManager.GetString("Msg_Fed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food can only contain letters, spaces and dashes..
        /// </summary>
        public static string Msg_FoodInvalid {
            get {
                return ResourceManager.GetString("Msg_FoodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter food..
        /// </summary>
        public static string Msg_FoodRequired {
            get {
                return ResourceManager.GetString("Msg_FoodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined enclosure.
        /// </summary>
        public static string Msg_JoinedEnclosure {
            get {
                return ResourceManager.GetString("Msg_JoinedEnclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log is already empty..
        /// </summary>
        public static string Msg_LogEmpty {
            get {
                return ResourceManager.GetString("Msg_LogEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs saved..
        /// </summary>
        public static string Msg_LogsSaved {
            get {
                return ResourceManager.GetString("Msg_LogsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can contain only letters, spaces and dashes..
        /// </summary>
        public static string Msg_NameInvalid {
            get {
                return ResourceManager.GetString("Msg_NameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name..
        /// </summary>
        public static string Msg_NameRequired {
            get {
                return ResourceManager.GetString("Msg_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night event started..
        /// </summary>
        public static string Msg_NightStarted {
            get {
                return ResourceManager.GetString("Msg_NightStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night event stopped..
        /// </summary>
        public static string Msg_NightStopped {
            get {
                return ResourceManager.GetString("Msg_NightStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an animal first..
        /// </summary>
        public static string Msg_NoSelection {
            get {
                return ResourceManager.GetString("Msg_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected animal?.
        /// </summary>
        public static string Msg_RemoveConfirmText {
            get {
                return ResourceManager.GetString("Msg_RemoveConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Remove.
        /// </summary>
        public static string Msg_RemoveConfirmTitle {
            get {
                return ResourceManager.GetString("Msg_RemoveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal removed..
        /// </summary>
        public static string Msg_Removed {
            get {
                return ResourceManager.GetString("Msg_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log is empty..
        /// </summary>
        public static string Msg_SaveLogEmpty {
            get {
                return ResourceManager.GetString("Msg_SaveLogEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select animal kind..
        /// </summary>
        public static string Msg_SelectKind {
            get {
                return ResourceManager.GetString("Msg_SelectKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is sleeping peacefully.
        /// </summary>
        public static string Msg_Sleeping {
            get {
                return ResourceManager.GetString("Msg_Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string Msg_Sound {
            get {
                return ResourceManager.GetString("Msg_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average age: {0}.
        /// </summary>
        public static string Msg_StatsAverageAge {
            get {
                return ResourceManager.GetString("Msg_StatsAverageAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} (avg {2}).
        /// </summary>
        public static string Msg_StatsByKind {
            get {
                return ResourceManager.GetString("Msg_StatsByKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest: {0} ({1}).
        /// </summary>
        public static string Msg_StatsOldest {
            get {
                return ResourceManager.GetString("Msg_StatsOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal.
        /// </summary>
        public static string Ui_AddAnimal {
            get {
                return ResourceManager.GetString("Ui_AddAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Ui_AddDialog_Age {
            get {
                return ResourceManager.GetString("Ui_AddDialog_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Ui_AddDialog_Cancel {
            get {
                return ResourceManager.GetString("Ui_AddDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Ui_AddDialog_Kind {
            get {
                return ResourceManager.GetString("Ui_AddDialog_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add name.
        /// </summary>
        public static string Ui_AddDialog_Name {
            get {
                return ResourceManager.GetString("Ui_AddDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ui_AddDialog_Ok {
            get {
                return ResourceManager.GetString("Ui_AddDialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal.
        /// </summary>
        public static string Ui_AddDialog_Title {
            get {
                return ResourceManager.GetString("Ui_AddDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Ui_Age {
            get {
                return ResourceManager.GetString("Ui_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Ui_All {
            get {
                return ResourceManager.GetString("Ui_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string Ui_Animals {
            get {
                return ResourceManager.GetString("Ui_Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird.
        /// </summary>
        public static string Ui_Bird {
            get {
                return ResourceManager.GetString("Ui_Bird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        public static string Ui_Cat {
            get {
                return ResourceManager.GetString("Ui_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        public static string Ui_ClearLog {
            get {
                return ResourceManager.GetString("Ui_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crazy action.
        /// </summary>
        public static string Ui_CrazyAction {
            get {
                return ResourceManager.GetString("Ui_CrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Ui_Details {
            get {
                return ResourceManager.GetString("Ui_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        public static string Ui_Dog {
            get {
                return ResourceManager.GetString("Ui_Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Food.
        /// </summary>
        public static string Ui_DropFood {
            get {
                return ResourceManager.GetString("Ui_DropFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string Ui_Feed {
            get {
                return ResourceManager.GetString("Ui_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by kind:.
        /// </summary>
        public static string Ui_FilterByKind {
            get {
                return ResourceManager.GetString("Ui_FilterByKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Ui_Food {
            get {
                return ResourceManager.GetString("Ui_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string Ui_Kind {
            get {
                return ResourceManager.GetString("Ui_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Ui_Log {
            get {
                return ResourceManager.GetString("Ui_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sound.
        /// </summary>
        public static string Ui_MakeSound {
            get {
                return ResourceManager.GetString("Ui_MakeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Ui_Name {
            get {
                return ResourceManager.GetString("Ui_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Crazy Action.
        /// </summary>
        public static string Ui_NoCrazyAction {
            get {
                return ResourceManager.GetString("Ui_NoCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove animal.
        /// </summary>
        public static string Ui_RemoveAnimal {
            get {
                return ResourceManager.GetString("Ui_RemoveAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Logs.
        /// </summary>
        public static string Ui_SaveLogs {
            get {
                return ResourceManager.GetString("Ui_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Night.
        /// </summary>
        public static string Ui_StartNight {
            get {
                return ResourceManager.GetString("Ui_StartNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Ui_Stats {
            get {
                return ResourceManager.GetString("Ui_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Night.
        /// </summary>
        public static string Ui_StopNight {
            get {
                return ResourceManager.GetString("Ui_StopNight", resourceCulture);
            }
        }
    }
}
